### ISSUE TITLE
excluding a directory from being searched

### ISSUE THREAD

**Issue by asmallteapot** [facebookincubator/fastmod#11]
Hi there! Is there a way to exclude a subdirectory from being searched, like `ack`'s `--ignore-dir=` option?

**Comment by swolchok** [comment]
You can do this with the `--glob` option. It plumbs into the `ignore` crate's glob support, which is [documented](https://docs.rs/ignore/0.4.3/ignore/overrides/struct.OverrideBuilder.html#method.add) to "have precisely the same semantics as a single line in a gitignore file, where the meaning of ! is inverted: namely, ! at the beginning of a glob will ignore a file". [gitignore documentation](https://git-scm.com/docs/gitignore) says that putting a slash at the end of a pattern makes it match only directory names, so:

```
$ cd /tmp
$ mkdir fmtest
$ cd fmtest
$ ls
$ mkdir yes
$ mkdir no
$ yes/a.txt
$ no/a.txt
$ fastmod hello goodbye -g '!no/'
./yes/a.txt:1
- hello
+ goodbye

Accept change (y = yes [default], n = no, e = edit, A = yes to all, E = yes+edit, q = quit)?
n
$ mkdir subdir
$ mv no yes subdir
$ fastmod hello goodbye -g '!no/'
./subdir/yes/a.txt:1
- hello
+ goodbye

Accept change (y = yes [default], n = no, e = edit, A = yes to all, E = yes+edit, q = quit)?
n
```

Hope this helps!
