### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by zoidbergwill** [facebookincubator/fastmod#14]

**Comment by ngirard** [comment]
My PR #19 would solve this.
@swolchok, would you mind taking a look to it ?

**Comment by swolchok** [comment]
Per my comment on #19:

> My high-level feedback is that I don't think that there is enough demand for binaries for this tool to make it worth the time spent reviewing and maintaining infrastructure to ship them. For example, brew info fastmod on my Mac tells me that 1) a homebrew formula for fastmod exists (wow!) and 2) it doesn't see much usage -- 13 installs in last 30 days, 56 in last 90 days, 116 in last 365 days. I can't find packages for Debian/Ubuntu or Windows at all with some quick Googling.

I would be happy to reconsider if I heard reasons why providing binaries would make a big difference. Thanks for raising the issue!
