### ISSUE TITLE
--extensions can't be used to match files with no extension, like BUCK or Makefile

### ISSUE THREAD

**Issue by swolchok** [facebookincubator/fastmod#2]
The solution to this is probably to support `-g`/`--glob` like `ripgrep`, since we use the `ignore` crate to implement `--extensions` anyway and we could just implement `-g` with passthrough to `ignore`.

**Comment by swolchok** [comment]
While we're at it, we might as well support `--iglob` too.

**Comment by gsquire** [comment]
I can take a shot at this. Reading some of the ripgrep documentation I see that globs take precedence over other matching logic. So if the user opts for `glob` or `iglob`, it would be used instead of extensions. Do you want to copy this behavior for fastmod?

**Comment by swolchok** [comment]
Sounds great to me! It would probably be best to state that each of `glob` and `iglob` [conflicts_with](https://docs.rs/clap/2.31.2/clap/struct.Arg.html#method.conflicts_with) `extensions`.
