### ISSUE TITLE
Feature request: Git integration

### ISSUE THREAD

**Issue by tsoernes** [facebookincubator/fastmod#20]
It would be nice with an option to automatically stage changed lines (only) to git.

Thanks for a great tool!

**Comment by swolchok** [comment]
What's the use case for having modified files in your checkout before running fastmod? That seems dangerous -- an error in your fastmod invocation could clobber your unstaged changes. Why not commit first?

**Comment by tsoernes** [comment]
I often have lots of unstaged changes laying around for a long time; only a
affecting files which are not applicable to my fastmod use case. Then, when
fastmodding lots of files it is time consuming to pick out the files
affected by the fastmod invocation.

**Comment by swolchok** [comment]
Would running with `fastmod foo bar --accept-all --print-changed-files | xargs git add` solve this?

**Comment by tsoernes** [comment]
That's a pretty good start at least. Thanks!

**Comment by swolchok** [comment]
Sounds like you're happy, so closing. Thanks for asking!
