### ISSUE TITLE
Feature Request: support "--fixed-strings" for substitute string

### ISSUE THREAD

**Issue by jduan** [facebookincubator/fastmod#22]
It seems like there's no way to supply a fixed string as the substitute string. Can this be added? When a fixed string is used as the regex, it's not uncommon that you would want to use a fixed substitute string as well. Thanks!

**Comment by Treit** [comment]
Isn't the substitute string already a fixed string?

**Comment by jduan** [comment]
Thanks for the quick response. I can't recall what I was trying to do and what trouble I had. Now I can't think of a use case. I'll close it for now.
