### ISSUE TITLE
Option to include hidden files

### ISSUE THREAD

**Issue by sluongng** [facebookincubator/fastmod#25]
Right now fastmod ignore hidden files unless we specifically list them in the file list.

For example running `fastmod 'target' 'targets'` on this very repo will skip out on https://github.com/facebookincubator/fastmod/blob/master/.gitignore file.

Please provide an option to match hidden file.

**Comment by swolchok** [comment]
Thanks for reporting this! It looks like we are missing equivalents to ripgrep's `--no-ignore` and `--hidden` options per https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering .

**Comment by swolchok** [comment]
I'm not going to add `--no-ignore` for now because it's part of a large-ish set of ripgrep options and I'd rather not open that particular can of worms, but `--hidden` should hopefully be coming soon.
