### ISSUE TITLE
Publish fastmod to Docker Hub, so that it can be used in container-based codemodding frameworks

### ISSUE THREAD

**Issue by kkom** [facebookincubator/fastmod#29]
I am wondering if it would be possible publish fastmod to Docker Hub in some official capacity, so that it could be used verbatim in the Sourcegraph batch changes spec?

This whole batch changes codemodding framework is container-based, similar to how Google Cloud Build configs work:

https://docs.sourcegraph.com/batch_changes/quickstart#write-a-batch-spec

Is this something Facebook ever does for other open source tools? I realize this can be done unofficially fairly easily, but an official image would be nice.

For example, https://github.com/comby-tools/comby/ is published to https://hub.docker.com/r/comby/comby (well, no wonder, since the main author is at Sourcegraph :) )

**Comment by swolchok** [comment]
I am completely unfamiliar with Docker, so realistically I am unlikely to do this. Sorry!

**Comment by kkom** [comment]
That's fair, thanks for the the quick reply @swolchok! Tupperware isn't a thing outside of Facebook unfortunately ;)

Feel free to close the issue, unless you think that at some point you might want to revisit this

**Comment by ngirard** [comment]
@kkom: I submitted last year a [working PR](https://github.com/facebookincubator/fastmod/pull/19) that allowed GitHub Actions to make precompiled binaries, and it was rejected with the following excuse:

> I don't think that there is enough demand for binaries for this tool to make it worth the time spent reviewing and maintaining infrastructure to ship them.

That's hilarious. Yeah right folks, keep pretending you play nice by throwing some code to a GitHub Repo, but don't spend an extra dime making it *actually* usable and valuable to people. Keep going !

**Comment by kkom** [comment]
A workaround that works for my use case is to just build an ad-hoc generic script to publish various tools to Docker Hub as I need them, it's actually pretty simple: https://github.com/kkom/tools-docker

See the PR where I added fastmod (and actually the whole setup too): https://github.com/kkom/tools-docker/pull/1

**Comment by ngirard** [comment]
@kkom Well then, we're both perfectly capable of packaging and running this software by ourselves, but this is not the point here.
The point is that some packaging is provided *upstream*, so people can benefit from it.
