### ISSUE TITLE
Allow deletion

### ISSUE THREAD

**Issue by sluongng** [facebookincubator/fastmod#32]
when I was trying to remove a matched set of configurations, I realized that fastmod default replacing the config with an empty line instead:

```
fastmod 'some-matching-config.*\n.*\n.*\n' ''
```

It would be nice to have a `--delete` flag that, instead of replacing existing matches with an empty line, it would just delete the matching lines.

**Comment by swolchok** [comment]
Fastmod doesn't try to insert extra lines, it just does the replacement you specify.
Couple potential fixes:
1) Did you try the `-m` option?
2) Perhaps you needed to match and remove one extra newline character?
